export const E_ACCESS = 'Access denied'
export const E_INVALID_ACTION = 'Invalid action'
export const E_INVALID_TOKEN = 'Invalid token'
export const E_UNIMPL = 'Unimplemented'
export const E_NOT_GLOBAL_META = 'Not global meta'
export const DEFAULT_PASS = 'adminadmin'
export const DEFAULT_USER = 'admin'
export const DEFAULT_EMAIL = 'admin@zhangzisu.cn'
